<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7SMJUAE" name="testNG.TestNGTimeOut" tests="2" failures="0" timestamp="10 May 2019 11:57:21 GMT" time="3.069" errors="1">
  <testcase name="TestOne" time="2.034" classname="testNG.TestNGTimeOut"/>
  <testcase name="TestTwo" time="1.035" classname="testNG.TestNGTimeOut">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.TestTwo() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.TestTwo() didn't finish within the time-out 1000
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- TestTwo -->
</testsuite> <!-- testNG.TestNGTimeOut -->
